name: Build and Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:

jobs:
  make_simple:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Simple
      run: make simple
  make_fixed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Fixed
      run: make fixed
  make_variable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Variable
      run: make variable
  test_simple:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Update references
    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
    - name: Build Tests for Simple and Run
      run: make test_simple
  test_fixed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Update references
    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
    - name: Build Tests for Fixed and Run
      run: make test_fixed
  test_variable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Update references
    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
    - name: Build Tests for Variable and Run
      run: make test_variable
